#
# Copyright 2026 The OKDP Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

################ Version Compatibility Matrix ######################
##### SECTION USED TO GET COMPATIBLE VERSIONS ######################
##### DONT PUT python_version IN AN ARRAY - JAVA COMPATIBILITY #####
####### ENRICH WITH NEWER VERSIONS #################################
compatibility-matrix:
  # Maximum python version supported by spark-3.2.x: 3.9
  # Java support: 8/11
  - python_version: 3.9
    spark_version: [3.2.1, 3.2.2, 3.2.3, 3.2.4]
    java_version: [11]
    scala_version: [2.12, 2.13]
    hadoop_version: 3.2
    # spark_download_url: https://archive.apache.org/dist/spark/
    spark_download_url: https://github.com/OKDP/spark-images/releases/download/spark-tarballs/
  # Maximum python version supported by spark-3.3.x: 3.10
  # Java support: 8/11/17
  - python_version: '3.10'
    spark_version: [3.3.1, 3.3.2, 3.3.3, 3.3.4]
    java_version: [17]
    scala_version: [2.12, 2.13]
    hadoop_version: 3
    # spark_download_url: https://archive.apache.org/dist/spark/
    spark_download_url: https://github.com/OKDP/spark-images/releases/download/spark-tarballs/
  # Maximum python version supported by spark-3.4.x: 3.11
  # Java support: 8/11/17
  - python_version: 3.11
    spark_version: [3.4.1, 3.4.2, 3.4.3, 3.4.4]
    java_version: [17]
    scala_version: [2.12, 2.13]
    hadoop_version: 3
    # spark_download_url: https://archive.apache.org/dist/spark/
    spark_download_url: https://github.com/OKDP/spark-images/releases/download/spark-tarballs/
  # https://spark.apache.org/releases/spark-release-3-5-0.html
  # Minimum supported java version: 17/21
  - python_version: 3.11
    spark_version: [3.5.1, 3.5.2, 3.5.3, 3.5.4, 3.5.5, 3.5.6]
    java_version: [17]
    scala_version: [2.12, 2.13]
    hadoop_version: 3
    # spark_download_url: https://archive.apache.org/dist/spark/
    spark_download_url: https://github.com/OKDP/spark-images/releases/download/spark-tarballs/
  # Minimum supported java version: 17/21
  # Support was dropped for 2.12 since spark 4
  # Maximum python version supported by spark-4.0.x: 3.13
  - python_version: 3.12
    spark_version: [4.0.0, 4.0.1]
    java_version: [17]
    scala_version: [2.13]
    hadoop_version: 3
    # spark_download_url: https://archive.apache.org/dist/spark/
    spark_download_url: https://github.com/OKDP/spark-images/releases/download/spark-tarballs/
  - python_version: 3.13
    spark_version: [4.0.0, 4.0.1]
    java_version: [17]
    scala_version: [2.13]
    hadoop_version: 3
    # spark_download_url: https://archive.apache.org/dist/spark/
    spark_download_url: https://github.com/OKDP/spark-images/releases/download/spark-tarballs/
### Override the matrix above by providing the versions to build
### 1- The build-matrix is empty: build with all possible combintations
### 2- Override specific versions: build with all possible combinations which are compatible with that specific versions
### 3- The versions not present on compatibility-matrix are ignored
### Check the supported versions: https://github.com/OKDP/spark-images/releases/tag/spark-tarballs
build-matrix:
  python_version: ['3.11', '3.12']
  spark_version: [3.4.2, 3.5.6]
  java_version: [17]
  scala_version: [2.12, 2.13]
